#!/bin/bash

### Grupo: SO-TI-18
### Aluno 1: Luís Lima (fc62214)
### Aluno 2: Gonçalo Seguro (fc62252)
### Aluno 3: Dinis Garcia (fc62269)

PYTHON="python3" # Pode-se modificar esta variavel, se necessario
PROGRAM="pword.py" # Nao pode modificar esta variavel
#TO-DO: Validar o número de argumentos antes de chamar o Python (Ver TP02)
#TO-DO: Validar que o ficheiro $PROGRAM existe antes de chama-lo (Ver TP02)

file_counter=0
process_true=false
process_number=1
m_mode=c
w_word=""
txt_files=""
interval=3
log_file=""

if [ ! -f "$PROGRAM" ]; then
    echo "Error: This program does not exist"
    exit 1
else
    # Check if any arguments were provided
    if [ $# -eq 0 ]; then
        echo "You need to provide arguments."
        exit 1
    else # Check if the right arguments were provided and selects the mode on how the word will be searched
        args=("$@")
        length=${#args[@]}
        for ((i=0; i<length; i++)); do
            arg="${args[i]}"
            if [ -f "$arg" ] && [[ "$arg" == *.txt ]]; then
                txt_files+="$arg " 
                ((file_count++))
            fi
            case $arg in 
                "-m")
                    m_mode="${args[i+1]}"
                    ;;
                "-w")
                    w_word="${args[i+1]}"
                    ;;
                "-p")
                    process_number="${args[i+1]}"
                    ;;
                "-i")
                    interval="${args[i+1]}"
                    ;;
                "-d")
                    log_file="${args[i+1]}"
                    ;;
            esac      
        done
        if [ "$txt_files" = "" ] || [ "$w_word" = "" ] ; then
            echo "The arguments must include a "-w word" argument and a .txt argument."
            exit 1
        fi
    fi
fi

#Checks if the number of processes is greater or equal of the number of files
if [ "$file_count" -gt 1 ] && [ "$process_number" -gt "$file_count" ];then
    echo "For multiple files, the number of processes can't be greater that the number of files."
    echo "Redefining number of processes to be the number of files."
    process_number="$file_count"
fi    
${PYTHON} ${PROGRAM} "$m_mode" "$process_number" "$interval" "$log_file" "$w_word" $txt_files 
exit 0
